### ISSUE TITLE
Release scheme to pypi/testpypi not working

### ISSUE THREAD

**Issue by SteinHeselmans** [melexis/jira-juggler#1]

**Comment by SteinHeselmans** [comment]
legacy pypi/testpypi is not working anymore. This is what i do locally (after removing ~/.pypi.rc):

```
python setup.py sdist bdist_wheel
twine upload dist/*
```

No clue what to do for travis-ci...

**Comment by JasperCraeghs** [comment]
The test platform of PyPI requires different credentials compared to the production PyPI. Anyway, I think none of the credentials you put in the .travis-ci.yml were valid. I've removed the job to publish to test PyPI and fixed the credentials used to publish to the production PyPI.
