### ISSUE TITLE
Depends not created when JIRA issue uses "is blocked by" other issue

### ISSUE THREAD

**Issue by 0xBDEF** [melexis/jira-juggler#32]
@JasperCraeghs "Depends" is only added to the task in jira_export.tjp when the 'Dependency' or 'Dependent' relationship is used. If "is blocked by" or any other dependency is used, the "Depends" is not created.

**Comment by 0xBDEF** [comment]
@Ben2022 : Apparently I did not notice this, but this broke all the links which I created in JIRA where by default I use "Blocks" and "is blocked by". So all the links in the recent plans are only based on allocation of the same person.

**Comment by JasperCraeghs** [comment]
Please review and/or try out Pull Request #33
